### ISSUE TITLE
3D apps launched from launcher crash after leaving the play zone

### ISSUE THREAD

**Issue by catoni0** [threethan/LightningLauncher#15] opened 2023-09-08 06:32 UTC
I think the cause is the same as for crashing apps on standby, probably something to do with launching activity

**Comment by frootloop88** [comment] 2023-09-09 13:22
can confirm

**Comment by threethan** [comment] 2023-09-10 09:17
Stationary or roomscale boundary? Quest OS version?

Can you confirm this doesn't happen when the same app is launched from the default launcher? Guardian has a lot of issue. It seems unlikely that this is the fault of the launcher.

**Comment by frootloop88** [comment] 2023-09-10 09:19
I don't know what version. As I said it's the latest public test channel version. It happens when coming from standby and when changing from room scale to stationary or changing the boundary limits. It doesn't happen without your launcher and it doesn't happen with the quest app launcher app from side quest.

**Comment by catoni0** [comment] 2023-09-10 09:55
> Stationary or roomscale boundary? Quest OS version?
> Both. Firmware version is v56. 

> Can you confirm this doesn't happen when the same app is launched from the default launcher? Guardian has a lot of issue. It seems unlikely that this is the fault of the launcher.


>Of course I tested launching from default launcher. I am a software engineer myself, so I did proper testing before opening an issue. Last update broke all the launchers apart from yours and "Quest app launcher" 
Also sometimes crashing when I am using see-through function.

**Comment by threethan** [comment] 2023-09-10 10:28
Before a VR intent is launched, the launcher activity is killed completely, and cannot possibly do anything. This is clearly as issue with the Quest OS, even if the launcher is somehow bringing it out. I'm not doing anything all that special.

It's very strange that I can replicate neither this, nor the standby issue. I've tested pretty extensively when I was on v56.

If you don't mind, could you try launching `LightningLauncher -> QuestAppLauncher -> A VR Game` or `QuestAppLauncher -> LightningLauncher -> A VR Game` and see if the issue persists? If either works, I can work around it by creating a VR chainloader. If not, it might not be possible to fix.

Since you know what you're doing, it would be a great help if you could check logcat for anything out of the ordinary when the system locks up.

**Comment by threethan** [comment] 2023-09-10 11:15
After a few hours of trying different combinations, I think I may have replicated the issue.

It seems to occur if, and only if, using the specifically the 2.1 shortcut apk. When leaving the zone, you must wait for the prompt to appear to change your zone, then dismiss that prompt and attempt to return to the game. For some reason, this causes vrshell to restart itself. 

I still haven't had this happen when resuming from either sleep or standby, but this prompt may end up getting shown if you have poor tracking. I also haven't been able to get to where I need to reboot, but it's possible a newer PTR build fails to properly restart vrshell when it crashes.

I've narrowed this down to "finishOnTaskLaunch" being enabled in the manifest. I'm not quite sure how it's connected, given that the activity is already finished, the game is its own task, and the same line is present in the manifest of the launcher itself without issue. Nonetheless, removing it seems to resolve the problem.

Thanks @frootloop88 and @catoni0 for confirming this is specific to the launcher but not the OS version.

I've uploaded a new build of the shortcut apk, please confirm that this resolves your problem.

**Comment by catoni0** [comment] 2023-09-10 11:53
> It seems to occur if, and only if, using the specifically the 2.1 shortcut apk.

Actually I was just testing this theory, but unfortunately shortcut apk has nothing to do with it.  
I've tried launching launcher from unknown sources directly - issue persist. 
Also I just completely removed launcher and shortcut and did a clean install with a hotfix, just to be sure. 

> wait for the prompt to appear to change your zone, then dismiss that prompt and attempt to return to the game
Indeed this is exact moment when the issue occurs

> LightningLauncher -> QuestAppLauncher -> A VR Game or QuestAppLauncher -> LightningLauncher -> A VR Game

In first case it behaves like any other 3D app, since this is a 3D launcher
Second case is not possible to test, since 2D apps launching functionality appears to be broken. 

> Since you know what you're doing, it would be a great help if you could check logcat for anything out of the ordinary when the system locks up.

I will keep you posted if I find anything. 

Also, there is a PC qLoader app for downloading apks for Quest, that is only accessible via russian VPN for some reason and they have a recent launcher that is seems to be a 2 in 1 combination of PiLauncher and your launcher (but it's launched via help shortcut) Whatever they did to the piLauncher it seems to be fixed the issue (your launcher with half russian translation behaves the same tho) 
I fetched it for you, maybe you will find something in manifest, as I doubt I will find any source codes
[](url)
[! App Launcher [RUS - 56 ready - QGO compatible] v303+3.0.3.zip](https://github.com/threethan/LightningLauncher/files/12568133/App.Launcher.RUS.-.56.ready.-.QGO.compatible.v303%2B3.0.3.zip)

**Comment by frootloop88** [comment] 2023-09-10 11:58
why was my post removed??

**Comment by frootloop88** [comment] 2023-09-10 14:16
> > It seems to occur if, and only if, using the specifically the 2.1 shortcut apk.
> 
> Actually I was just testing this theory, but unfortunately shortcut apk has nothing to do with it. I've tried launching launcher from unknown sources directly - issue persist. Also I just completely removed launcher and shortcut and did a clean install with a hotfix, just to be sure.
> 
> > wait for the prompt to appear to change your zone, then dismiss that prompt and attempt to return to the game
> > Indeed this is exact moment when the issue occurs
> 
> > LightningLauncher -> QuestAppLauncher -> A VR Game or QuestAppLauncher -> LightningLauncher -> A VR Game
> 
> In first case it behaves like any other 3D app, since this is a 3D launcher Second case is not possible to test, since 2D apps launching functionality appears to be broken.
> 
> > Since you know what you're doing, it would be a great help if you could check logcat for anything out of the ordinary when the system locks up.
> 
> I will keep you posted if I find anything.
> 
> Also, there is a PC qLoader app for downloading apks for Quest, that is only accessible via russian VPN for some reason and they have a recent launcher that is seems to be a 2 in 1 combination of PiLauncher and your launcher (but it's launched via help shortcut) Whatever they did to the piLauncher it seems to be fixed the issue (your launcher with half russian translation behaves the same tho) I fetched it for you, maybe you will find something in manifest, as I doubt I will find any source codes [! App Launcher [RUS - 56 ready - QGO compatible] v303+3.0.3.zip](https://github.com/threethan/LightningLauncher/files/12568133/App.Launcher.RUS.-.56.ready.-.QGO.compatible.v303%2B3.0.3.zip)
> 
> Update: Somebody just used your launching method in the PiNextLauncher and it works without any issues, so the bug is elsewhere.... [PiLauncherHotFixTest.zip](https://github.com/threethan/LightningLauncher/files/12568192/PiLauncherHotFixTest.zip)

works great thanks. shortcut doesn't work though, correct?

**Comment by catoni0** [comment] 2023-09-10 14:36
@frootloop88
Only with replacing explore app via accessibility services (also need to disable original)

**Comment by frootloop88** [comment] 2023-09-10 15:27
> @frootloop88 Only with replacing explore app via accessibility services (also need to disable original)

how to disable explorer app?

**Comment by catoni0** [comment] 2023-09-10 15:48
Settings (pi icon), system tweaks, explore app
Then you will have disable button.

You can also reach it via android settings (from launcher) and apps

**Comment by threethan** [comment] 2023-09-10 23:00
> > It seems to occur if, and only if, using the specifically the 2.1 shortcut apk.
> 
> Actually I was just testing this theory, but unfortunately shortcut apk has nothing to do with it. I've tried launching launcher from unknown sources directly - issue persist. Also I just completely removed launcher and shortcut and did a clean install with a hotfix, just to be sure.
> 
> > wait for the prompt to appear to change your zone, then dismiss that prompt and attempt to return to the game
> > Indeed this is exact moment when the issue occurs
> 
> > LightningLauncher -> QuestAppLauncher -> A VR Game or QuestAppLauncher -> LightningLauncher -> A VR Game
> 
> In first case it behaves like any other 3D app, since this is a 3D launcher Second case is not possible to test, since 2D apps launching functionality appears to be broken.
> 
> > Since you know what you're doing, it would be a great help if you could check logcat for anything out of the ordinary when the system locks up.
> 
> I will keep you posted if I find anything.
> 
> Also, there is a PC qLoader app for downloading apks for Quest, that is only accessible via russian VPN for some reason and they have a recent launcher that is seems to be a 2 in 1 combination of PiLauncher and your launcher (but it's launched via help shortcut) Whatever they did to the piLauncher it seems to be fixed the issue (your launcher with half russian translation behaves the same tho) I fetched it for you, maybe you will find something in manifest, as I doubt I will find any source codes [! App Launcher [RUS - 56 ready - QGO compatible] v303+3.0.3.zip](https://github.com/threethan/LightningLauncher/files/12568133/App.Launcher.RUS.-.56.ready.-.QGO.compatible.v303%2B3.0.3.zip)
> 
> Update: Somebody just used your launching method in the PiNextLauncher and it works without any issues, so the bug is elsewhere.... [PiLauncherHotFixTest.zip](https://github.com/threethan/LightningLauncher/files/12568192/PiLauncherHotFixTest.zip)

This is immensely useful. Then only notable differences between these and mine seem to be interface changes and manifest differences. I've reverted the manifest to be much more similar to those versions, which should hopefully fix the issue.

I've posted this build to releases and would appreciate if you could test it.

**Comment by catoni0** [comment] 2023-09-11 14:19
@threethan , tested new version, still crashing. 
Also it keeps asking to update each time I start it, probably didn't update the manifest to 4.0.2 and this results infinite update prompt loop :D

**Comment by threethan** [comment] 2023-09-11 18:35
Other way around, build was updated to far. Caught & fixed before you
mentioned, you can do a hard reinstall from the APK that's up now or just
wait for the next actual update when I actually manage to fix things

**Comment by ValentineShilov** [comment] 2023-09-11 20:26
I am the developer of PiLauncherHotFixTest. I used the same way to launch 3D apps as in your launcher (launching activity from a timer task) , so the problem is not in the way of launching the activity.
`            Intent launchIntent = context.getPackageManager().getLaunchIntentForPackage(app.packageName);
            if (launchIntent != null) {
                if (SettingsProvider.getAppLaunchOut(app.packageName)) {
                    ((Activity) context).finish();
                    new Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                           	context.startActivity(launchIntent);                          
                        }
                    }, 650);
                } else {
                    context.startActivity(launchIntent);
                }
                return true;
            } else {
                Log.e("runApp", "Failed to launch - NULL launchIntent");
                return false;
            }`


> Update:
> Somebody just used your launching method in the PiNextLauncher and it works without any issues, so the bug is elsewhere....
Just in case, there is a newer version with all the fixes (working tabs, launching always works, settings exporting)
[PiLauncherNextHotfix3.zip](https://github.com/threethan/LightningLauncher/files/12580043/PiLauncherNextHotfix3.zip)

**Comment by threethan** [comment] 2023-09-11 22:07
@ValentineShilov Thank you! There are actually a few differences between that and how I do things now, which may actually be the problem.

You're under no obligation, but it would be great if you could make your fork public as well. I can link it under related projects in the readme.

**Comment by threethan** [comment] 2023-09-13 00:36
I seem to have narrowed it down and the cause was bumping the android API.

I reverted to API level 23 and it should fix the issue, for real this time.

I've done a decent bit of testing since and I have managed to still get into a similar lockup, but only by aggressively messing with tasks and multi-window in a way I doubt will come up naturally.

I'll keep the thread open until I have some proper confirmation.

**Comment by ValentineShilov** [comment] 2023-09-13 10:42
> but it would be great if you could make your fork public as well

Created the repository: [https://github.com/ValentineShilov/PiLauncherNG](https://github.com/ValentineShilov/PiLauncherNG)

**Comment by threethan** [comment] 2023-09-18 13:03
Since I've attempted a fix and there's no indication this issue is still present, I'm going to close this thread. Open a new issue if something similar arises.

**Closed by threethan** 2023-09-18 13:03 UTC

**Comment by catoni0** [comment] 2023-09-23 04:06
All good now, 
Thanks for your hard work!
