### ISSUE TITLE
System interface crashes or restarts when resuming from standby after a VR Application is launched

### ISSUE THREAD

**Issue by frootloop88** [threethan/LightningLauncher#14] opened 2023-09-06 13:04 UTC
Love your app but if I play a game and put the headset down/standby and put it back on the game often is just black and not even the oculus menu appears. Is this fixable?

**Comment by niktn10** [comment] 2023-09-07 16:33
I have the same problem, but not a black screen, but just throws me out of the game.

**Comment by threethan** [comment] 2023-09-10 09:14
I think I've experienced this before. When you see the black screen, what happens when you press the home button? Does the app return?

Please confirm this same issue does not occur when opening the same game from the default launcher. If it does, *this is an issue with the Quest's OS and not this launcher.*

If not, what are the Quest OS and Launcher versions? Does this happen consistently or only on occasion?

**Comment by frootloop88** [comment] 2023-09-10 09:16
> 

It happens every time for me. I am on 57 public test channel. If I press the home button nothing happens. I have to reboot my quest 2

**Comment by threethan** [comment] 2023-09-10 09:19
Does it happen when using the default launcher? (If you have the shortcut service activated for LightningLauncher, disable it)

**Comment by frootloop88** [comment] 2023-09-10 09:20
> Does it happen when using the default launcher? (If you have the shortcut service activated for LightningLauncher, disable it)

NO

**Comment by threethan** [comment] 2023-09-10 09:22
Odd. Can you provide specific steps to replicate? This seems like a serious issue but I cannot replicate it for the life of me

**Comment by frootloop88** [comment] 2023-09-10 09:23
I already did in my first post

**Comment by frootloop88** [comment] 2023-09-10 09:26
maybe ask the dev of this launcher, it works (ugly UI though lol)

https://sidequestvr.com/app/199/quest-app-launcher

**Comment by threethan** [comment] 2023-09-10 09:50
> Love your app but if I play a game and put the headset down/standby and put it back on the game often is just black and not even the oculus menu appears. Is this fixable?

- Taking the headset off (sleep) and pressing the power button (standby) are different states. (Are you referring to both?)

- How is LightningLauncher being opened? (Shortcut APK, Shortcut Service, or from Unknown Sources)

- In Quick Settings, is "Switch View" highlighted? This setting has been known to cause issues with launching apps in the past.

- Does this occur with 2D apps, or only with full VR apps? Please list a few games or applications you have tried so that I can verify.

- Meta is well known for A/B testing updates. I am on system version 50623410042600150. This is the latest PTR available to me, but the latest version for you may differ.

I need to be able to replicate this issue on my device to be able to fix it.

**Comment by threethan** [comment] 2023-09-10 11:16
After a few hours of trying different combinations, I think I may have replicated the issue.

It seems to occur if, and only if, using the specifically the 2.1 shortcut apk. When leaving the zone, you must wait for the prompt to appear to change your zone, then dismiss that prompt and attempt to return to the game. For some reason, this causes vrshell to restart itself. 

I still haven't had this happen when resuming from either sleep or standby, but this prompt may end up getting shown if you have poor tracking. I also haven't been able to get to where I need to reboot, but it's possible a newer PTR build fails to properly restart vrshell when it crashes.

I've narrowed this down to "finishOnTaskLaunch" being enabled in the manifest. I'm not quite sure how it's connected, given that the activity is already finished, the game is its own task, and the same line is present in the manifest of the launcher itself without issue. Nonetheless, removing it seems to resolve the problem.

Thanks @frootloop88 and @catoni0 for confirming this is specific to the launcher but not the OS version.

I've uploaded a new build of the shortcut apk, please confirm that this resolves your problem.

**Comment by frootloop88** [comment] 2023-09-10 11:26
the problem is not the shortcut app at all. I just tested it again.

Launched breachers - pushed the standby button - quest goes to sleep  - push it again - back to breachers

if I do the same with your launcher or shortcut (doesn't matter) it always closes breachers and I am back at the Home Screen.

**Comment by threethan** [comment] 2023-09-11 02:58
**With your help I have managed to replicate the bug on a friend's headset.** I'm still working on properly identifying the cause, but a fix should be coming in the next few days.

**Comment by threethan** [comment] 2023-09-13 00:38
I think I've (at least mostly) fixed the issue by *downgrading* the android API. See if it's better now!

**Comment by threethan** [comment] 2023-09-18 13:03
Since I've attempted a fix and there's no indication this issue is still present, I'm going to close this thread. Open a new issue if something similar arises.

**Closed by threethan** 2023-09-18 13:03 UTC
