### ISSUE TITLE
Setting custom icon resets all custom icons

### ISSUE THREAD

**Issue by siskyn** [threethan/LightningLauncher#18] opened 2023-09-15 11:56 UTC
Context: Trying to set a custom icon for a app used for IPD calibration.
Result:  The icon does not get applied, and furthermore all previously set custom icons get reset to default.
Video:  [https://youtu.be/X9xZirU9rDw](https://youtu.be/X9xZirU9rDw)

Link to the apk of the app: [https://arcadia-labs.itch.io/oculusquest-ipd](https://arcadia-labs.itch.io/oculusquest-ipd)

**Comment by brupec** [comment] 2023-09-17 10:06
Hi, cannot really help with the issue, but was wondering how you set custom banners for apps.

I found the menu to do it but I just see "folder" with nothing in it, cannot navigate. which folder should the custom images be placed on the quest for them to be seen there ? Looked the history of releases and didn't find that info either.

Thanks in advance

**Comment by threethan** [comment] 2023-09-18 01:45
The issue was caused by a call to `clearIcons()` instead of `clearIconCache()`. It's been fixed and will be rolled out with 5.1 once I work out some unrelated issues.

Image picker is handled by an external library, but it _should_ pick up any images in any user-accessible directories. I'd recommend making a folder for custom icons in `storage/emulated/0/`, which is the root directory when connected over MTP.

**Comment by brupec** [comment] 2023-09-18 11:02
great, thanks it's working perfect. now I have same issue than siskyn so i'll wait for next release ;-) thanks for your great launcher!! I'll open another issue too

**Comment by threethan** [comment] 2023-09-18 13:52
Should be fixed as of 5.1.0

**Closed by threethan** 2023-09-18 13:52 UTC
