### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ZAKsPop** [threethan/LightningLauncher#103] opened 2024-01-14 05:34 UTC
I know this was discussed before but that issue was deleted I guess. Anyway, is there a way to get the better icons to download? I have games now with blurry lowres icons that used to look good a couple versions back.

**Comment by threethan** [comment] 2024-01-16 05:07
A few issues about icons have been *closed,* not deleted. Please provide more information about your particular issue, preferably including screenshots.

**Comment by threethan** [comment] 2024-01-19 01:13
Duplicate of https://github.com/threethan/LightningLauncher/issues/97

App Lab games are not currently supported by any of the high-res icon repos.

**Closed** 2024-01-19 01:13 UTC
