### ISSUE TITLE
Can't install App Library Shortcut Service

### ISSUE THREAD

**Issue by natebragg** [threethan/LightningLauncher#132] opened 2024-04-15 18:31 UTC
I go to the install menu, click on install, and the app chooser dialog comes up.  When I choose "Open with app installer", then screen blanks and goes back to the menu.  Lightning launcher is closed.

I captured the adb output (with `adb logcat | grep com.threethan.launcher`):
[app-library-shortcut-bad-install.log](https://github.com/threethan/LightningLauncher/files/14983003/app-library-shortcut-bad-install.log)

Not sure if that's helpful.

**Comment by threethan** [comment] 2024-04-26 00:19
Do other shortcuts work? What happens if you attempt to install an apk on-device using another program, such as a file manager?

The log is helpful, as it shows the apk was successfully downloaded and the view intent was correctly passed to the system. However, it doesn't indicate that the APK installed was actually started. _(The 7th line in the log is from a component of LL itself)_ This strongly suggests the issue is not actually with Lightling Launcher.

I suspect that the issue was with the "open with" dialog. The quest's version of android seems to have issues with that dialog. If you uninstall any apps which attempt to open APK files, your issue _might_ be resolved.

**Comment by natebragg** [comment] 2024-04-26 00:31
It seems that you're right, but I'm not sure what to do.  There are no resources on this topic that I can find.  Although this appears not to be an LL issue, perhaps you could point me in the right direction to resolve this?  I'm not quite sure what to do to root cause it.

**Comment by threethan** [comment] 2024-04-26 00:40
When you opened that dialog, I assume you saw some number of apps alongside the package installer, try uninstalling these apps to prevent the dialog from appearing in the first place. As an alternate workaround, you may download the addon apk manually from the [latest addon release](https://github.com/threethan/LightningLauncher/releases/tag/addons7.0.0) and install it manually via adb.

Closing as 'not planned'.

**Closed by threethan** 2024-04-26 00:40 UTC
